# Generated by Django 2.2 on 2025-04-16 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rec', '0005_auto_20250416_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='glpost',
            name='username',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postusernames', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
    ]
