# Generated by Django 2.2 on 2025-04-05 08:54

from django.db import migrations, models
import rec.models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glpost',
            name='jattach',
            field=models.FileField(blank=True, default=None, null=True, upload_to=rec.models.get_file_path, verbose_name='Support Attachment'),
        ),
    ]
