# Generated by Django 2.2 on 2025-04-13 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rec', '0003_auto_20250411_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='gldetail',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gldetails_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='gldetail',
            name='username',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
    ]
