# Generated by Django 2.2 on 2025-04-16 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rec', '0004_auto_20250413_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='gldetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gldetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='glpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_glposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='glpost',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_glposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gldetail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gldetails', to=settings.AUTH_USER_MODEL),
        ),
    ]
